export const events = [
    "/posters/poster.jpeg",
    "/posters/poster.jpeg",
    "/posters/poster.jpeg",
    "/posters/poster.jpeg",
    "/posters/poster.jpeg",
    "/posters/poster.jpeg",
    // "/posters/poster.jpeg",
    // "/posters/poster.jpeg",
    // "/posters/poster.jpeg",
    // "/posters/poster.jpeg",
    // "/posters/poster.jpeg",
    // "/posters/poster.jpeg",
    // "/posters/poster.jpeg",
    // "/posters/poster.jpeg",
]